version: "3"
services:
  db:
    image: mysql:5.7
    build: 
      context:  ./
      dockerfile: Dockerfile-mysql
    volumes:
      - "./mysql:/var/lib/mysql"
    ports:
      - "3307:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=djangoproject

  app:
    restart: always
    build: 
      context:  ./
      dockerfile: Dockerfile
    command: bash -c "python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  